### ISSUE TITLE
 background mode

### ISSUE THREAD

**Issue by web75018** [umair13adil/simple_beacons_flutter#1]
Hi @umair13adil 
can we use the package on background mode (iOS / Android)?
Thanks for sharing!

**Comment by umair13adil** [comment]
HI,

No, that feature is not added yet, I will add it to my list and see if I can develop it soon.

Med venlig hilsen / Kind regards
 
Muhammad Umair Adil,
Sr. Software Engineer

**Comment by umair13adil** [comment]
I have published a new version (1.0.8) of the
beacons_plugin package to the Dart package site (pub.dev).

Background scan mode is added, please see ReadMe for implementation on Android & iOS project.

For details, go to https://pub.dev/packages/beacons_plugin/versions/1.0.8 <https://pub.dev/packages/beacons_plugin/versions/1.0.8>

If you have any concerns about this package, file an issue at
https://github.com/dart-lang/pub-dev/issues <https://github.com/dart-lang/pub-dev/issues>
