### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel beacons_plugin_stream)

### ISSUE THREAD

**Issue by mingjunsiek** [umair13adil/simple_beacons_flutter#15]
![image](https://user-images.githubusercontent.com/13094556/88156304-d3fe0c00-cc3b-11ea-96d6-e6f1b55a324e.png)

I've followed your steps in installing the plugin and I copied your example file to test it out. However, I faced this issue regarding MissingPluginException. Please advice.

**Comment by umair13adil** [comment]
Have you replaced the 'FlutterActivity' with 'BeaconsActivity' as shown in the code below?

```
class MainActivity : BeaconsActivity(){

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}
```

**Comment by mingjunsiek** [comment]
Ah right! Thank you!
