### ISSUE TITLE
version 1.0.15 - breaking changes 

### ISSUE THREAD

**Issue by dariocavada** [umair13adil/simple_beacons_flutter#17]
Please add some sort of alert for porting from 1.0.12 to 1.0.15, you have to remove some old code from the AndroidManifest and change the `MainActivity.kt` as shown in the documentation (Just to mention that if after upgrading the code did not compiles  you have to modifify AndroidManifest and MainActivity.kt.)

**Comment by umair13adil** [comment]
Okay, I will do that. I will add some sort of migration guide.
