### ISSUE TITLE
version 1.0.15 - setMethodCallHandler is never been called

### ISSUE THREAD

**Issue by dariocavada** [umair13adil/simple_beacons_flutter#18]
After upgrade to 1.0.15, the setMethodCallHandler never returns a value.

If you want to start beacon monitoring you have to manually call:

``` dart
await BeaconsPlugin.startMonitoring;
```

If you try this code (taken from your example), the code prints out just STEP1 and not STEP2 and STEP3:

``` dart
if (Platform.isAndroid) {
      print('****** STEP 1');
      BeaconsPlugin.channel.setMethodCallHandler((call) async {
        print('****** STEP 2');
        if (call.method == 'scannerReady') {
          print('****** STEP 3');
          await BeaconsPlugin.startMonitoring;
          setState(() {
            isRunning = true;
          });
        }
      });
    }
```

**Comment by umair13adil** [comment]
I will look into it, maybe 'scannerReady' method call is not properly invoked or blocked on the Android plugin side.

**Comment by EricHier** [comment]
I've got the same problem - did you find a solution?

**Comment by jangruenwaldt** [comment]
Yeah, if you use the code from the readme, it does not actually work. Specifically, _respondToCall is never called:
`if (Platform.isAndroid) {
      BeaconsPlugin.channel.setMethodCallHandler(_respondToCall);
}`

**Comment by VinniciusJesus** [comment]
@jangruenwaldt Could you give me a sample of the solution? I'm not getting

**Comment by jangruenwaldt** [comment]
> @jangruenwaldt Could you give me a sample of the solution? I'm not getting

Just use an older package version I think. Or it was fixed, not sure.

**Comment by barangungor** [comment]
Same issue. Did you fix ?
