### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by mike-robinson** [umair13adil/simple_beacons_flutter#2]
Could not build your example for iOS.

`Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                              1.7s
Running Xcode build...
Xcode build done.                                            6.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/beacons_plugin-umbrella.h"
            ^
    /Users/mrobinson/AndroidStudioProjects/shooter_flutter/ios/Pods/Target Support Files/beacons_plugin/beacons_plugin-umbrella.h:14:9: note: in file included from /Users/mrobinson/AndroidStudioProjects/shooter_flutter/ios/Pods/Target Support Files/beacons_plugin/beacons_plugin-umbrella.h:14:
    #import "Runner-Bridging-Header.h"
            ^
    /Users/mrobinson/flutter/.pub-cache/hosted/pub.dartlang.org/beacons_plugin-1.0.6/ios/Classes/Runner-Bridging-Header.h:1:9: error: 'GeneratedPluginRegistrant.h' file not found
    #import "GeneratedPluginRegistrant.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'beacons_plugin'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/beacons_plugin-umbrella.h"
            ^
    /Users/mrobinson/AndroidStudioProjects/shooter_flutter/ios/Pods/Target Support Files/beacons_plugin/beacons_plugin-umbrella.h:14:9: note: in file included from /Users/mrobinson/AndroidStudioProjects/shooter_flutter/ios/Pods/Target Support Files/beacons_plugin/beacons_plugin-umbrella.h:14:
    #import "Runner-Bridging-Header.h"
            ^
    /Users/mrobinson/flutter/.pub-cache/hosted/pub.dartlang.org/beacons_plugin-1.0.6/ios/Classes/Runner-Bridging-Header.h:1:9: error: 'GeneratedPluginRegistrant.h' file not found
    #import "GeneratedPluginRegistrant.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'beacons_plugin'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/beacons_plugin-umbrella.h"
            ^
    /Users/mrobinson/AndroidStudioProjects/shooter_flutter/ios/Pods/Target Support Files/beacons_plugin/beacons_plugin-umbrella.h:14:9: note: in file included from /Users/mrobinson/AndroidStudioProjects/shooter_flutter/ios/Pods/Target Support Files/beacons_plugin/beacons_plugin-umbrella.h:14:
    #import "Runner-Bridging-Header.h"
            ^
    /Users/mrobinson/flutter/.pub-cache/hosted/pub.dartlang.org/beacons_plugin-1.0.6/ios/Classes/Runner-Bridging-Header.h:1:9: error: 'GeneratedPluginRegistrant.h' file not found
    #import "GeneratedPluginRegistrant.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'beacons_plugin'
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.`

`mrobinson@development lib % flutter doctor -v
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.0 at /Users/mrobinson/flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mrobinson/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/mrobinson/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/mrobinson/Library/Android/sdk
    • Java binary at: /Users/mrobinson/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6308749/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/mrobinson/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6308749/Android
      Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Users/mrobinson/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.6668.156

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 71E1A5E8-1515-49B4-941E-F3C64455E234 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
mrobinson@development lib % 
`

**Comment by umair13adil** [comment]
Hi,

I have been reported this bug, I am working on it’s fix. I will release this within a day or two.

Med venlig hilsen / Kind regards
 
Muhammad Umair Adil,
Sr. Software Engineer

**Comment by umair13adil** [comment]
I have published a new version (1.0.8) of the
beacons_plugin package to the Dart package site (pub.dev).

iOS build issue is fixed, please see ReadMe for implementation on iOS project.

For details, go to https://pub.dev/packages/beacons_plugin/versions/1.0.8 <https://pub.dev/packages/beacons_plugin/versions/1.0.8>

If you have any concerns about this package, file an issue at
https://github.com/dart-lang/pub-dev/issues <https://github.com/dart-lang/pub-dev/issues>
Med venlig hilsen / Kind regards
 
Muhammad Umair Adil,
Sr. Software Engineer
