### ISSUE TITLE
App rejection - Android

### ISSUE THREAD

**Issue by dariocavada** [umair13adil/simple_beacons_flutter#28]
My App was rejected with this message:

**Prominent disclosure not found**
Your app must display a prominent disclosure through a pop-up alert before your app’s location runtime permission. Based on our review, a prominent disclosure did not appear before the runtime permission.

The Beacon Plugin needs the PERMISSION_REQUEST_BACKGROUND_LOCATION and so:

Your app must display a prominent disclosure through a pop-up alert before your app’s location runtime permission. Based on our review, a prominent disclosure did not appear before the runtime permission.

Please add a prominent disclosure before the runtime permission.

Remember, your prominent disclosure must:

- Appear before your app’s location runtime permission.

- Include at least the following sentence, adapted to include all the relevant features requesting access to location in the background in the app that are readily visible to the user: “This app collects location data to enable ["feature"], ["feature"], & ["feature"] even when the app is closed or not in use.” If you extend permitted usage to ads, please also include: “This data is also used to provide ads/support advertising/support ads.”

- Include any other details necessary to make it clear to the user how and why you are using location in the background. While additional content is permitted, it should not cause the required content to not be immediately visible.

I've seen some documentation on the altbeaconlibrary website:

https://altbeacon.github.io/android-beacon-library/requesting_permission.html

and also on google developer:

https://developer.android.com/training/permissions/requesting

<img width="907" alt="Schermata 2020-11-03 alle 11 34 07" src="https://user-images.githubusercontent.com/4304176/97974867-83fd1c80-1dc8-11eb-8993-4190d58e4c52.png">

And other docs for permission.

https://support.google.com/googleplay/android-developer/answer/9799150
https://support.google.com/googleplay/android-developer/answer/9888170/
https://support.google.com/googleplay/android-developer/answer/9888170#location-permissions
https://support.google.com/googleplay/android-developer/answer/9799150

Do you have any solution for this problem ?

**Comment by umair13adil** [comment]
The solution is one provided by AltBeacon, this must be added in the plugin for Android.

**Comment by dariocavada** [comment]
Any news on that ?

**Comment by umair13adil** [comment]
@dariocavada **'BACKGROUND_LOCATION'** permission is removed from the plugin project but can be added by the developer in their project. Also, the code to show **'Prominent disclosure'** is added just as provided by AltBeacon library. It will only run for Android projects with minSDkVersion 29. So, it shouldn't be added for projects running under that SDK version.

**Comment by dariocavada** [comment]
Thank you
