### ISSUE TITLE
App Rejection - iOS

### ISSUE THREAD

**Issue by dariocavada** [umair13adil/simple_beacons_flutter#29]
If you don't use the background mode (scanning beacons), you must remove the following lines from Info.plist: 

``` xml
<key>UIBackgroundModes</key>
<string>location</string>
```

The apple team rejected my app because of this.

You could put this advice in your documentation.

**Guideline 2.5.4 - Performance - Software Requirements**

Your app declares support for location in the UIBackgroundModes key in your Info.plist file but does not have any features that require persistent location. Apps that declare support for location in the UIBackgroundModes key in your Info.plist file must have features that require persistent location.

**Next Steps**

To resolve this issue, please revise your app to include features that require the persistent use of real-time location updates while the app is in the background.

If your app does not require persistent real-time location updates, please remove the "location" setting from the UIBackgroundModes key. You may wish to use the significant-change location service or the region monitoring location service if persistent real-time location updates are not required for your app features.

Resources

For more information, please review the Starting the Significant-Change Location Service and Monitoring Geographical Regions.

**Comment by yossefEl** [comment]
@dariocavada Thanks for sharing this advice!
Does this plugin works well on is for you??
it stucks in Stop Scanning for me and the scan is not working !

**Comment by dariocavada** [comment]
Yes it works, if you want to share your code, beacon used, phone, ... etc.

**Comment by yossefEl** [comment]
@dariocavada  thank you, unfortunately, it is not working on iOS for me, I used the example provided by the owner

**Comment by umair13adil** [comment]
@dariocavada 'UIBackgroundModes' is removed from the plugin project to prevent App rejection. It can be added by the developers in their code.
