### ISSUE TITLE
No beacons scanned

### ISSUE THREAD

**Issue by mike-robinson** [umair13adil/simple_beacons_flutter#3]
I'm running your example app on an iPhone. Runs fine but detects no beacons. I am using another app (BLE Hero) to insure that my beacon is actually transmitting (it is). I admit being very new to beacons but I have confirmed the UUID, major and minor regions and name of my beacon entered in the example code. There are no errors when running, just no results. Any suggestions?

**Comment by umair13adil** [comment]
On iPhone, it will only detect **'iBeacons',** other types like 'Eddystone', 'AltBeacon' are not detected at all.

Check out this answer on [StackOverflow](https://stackoverflow.com/a/46800813/6313469).

**Comment by mike-robinson** [comment]
Thanks for the reply. The beacon I am testing is an iBeacon (BlueCharm).

**Comment by dariocavada** [comment]
Same problem with iOS.

**Comment by cloudbreakstudios** [comment]
> I'm running your example app on an iPhone. Runs fine but detects no beacons. I am using another app (BLE Hero) to insure that my beacon is actually transmitting (it is). I admit being very new to beacons but I have confirmed the UUID, major and minor regions and name of my beacon entered in the example code. There are no errors when running, just no results. Any suggestions?

Hi @mike-robinson Where you able to get iOS scans detecting beacons?  I am trying to scan beacons without having to provide a UUID as our use case requires us to detect all beacons within range.  I raised this issue the other day as I've not been able to address this issue.  This plugin works fine on Android and detects beacons without needing to register UUID's, but again, iOS just isn't picking them up.

https://github.com/umair13adil/simple_beacons_flutter/issues/48
