### ISSUE TITLE
Used the new version (1.18) for my project , but still rejected from Google Play

### ISSUE THREAD

**Issue by dariocavada** [umair13adil/simple_beacons_flutter#32]
**Used the new version for my project, but still rejected from Google Play:**

I've compiled and I see the new dialog for permission, but I still have this from Google Play:

> Prominent disclosure not found
> Your app must display a prominent disclosure through a pop-up alert before your app’s location runtime permission. Based on our review, a prominent disclosure did not appear before the runtime permission.
> 
> Please add a prominent disclosure before the runtime permission.
> 
> Remember, your prominent disclosure must:
> Appear before your app’s location runtime permission.
> Include at least the following sentence, adapted to include all the relevant features requesting access to location in the background in the app that are readily visible to the user: “This app collects location data to enable ["feature"], ["feature"], & ["feature"] even when the app is closed or not in use.” If you extend permitted usage to ads, please also include: “This data is also used to provide ads/support advertising/support ads.”
> Include any other details necessary to make it clear to the user how and why you are using location in the background. While additional content is permitted, it should not cause the required content to not be immediately visible.

Any idea to solve this ?

Maybe using a plugin like this:
`https://pub.dev/packages/location_permissions`

**Features #**

- Check if permission to access location services is granted.
- Request permission to access location services.
- Open app settings so the user can allow permission to the location services.
- Show a rationale for requesting permission to access location services (Android).

**Comment by umair13adil** [comment]
@dariocavada What is your flutter project's Android minSDKVersion? 

The prominent disclosure message is added like this: **"Please grant location access so this app can detect beacons in the background."** Maybe this message is the reason. I will change it and release another update.

**Comment by dariocavada** [comment]
```
        minSdkVersion 24
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
```

**Comment by mingjunsiek** [comment]
I've updated to the new version but the prominent disclosure message is not working properly. Location permission was already given but this message is still popping up every time I run the app. I tried downgrading to the previous version but for some reason, the prominent disclosure message is still there.

**Comment by mingjunsiek** [comment]
Is there a way for you to let us create our own permission message instead of using the one you created?

**Comment by umair13adil** [comment]
@mingjunsiek Yes, that is exactly what I was thinking. I will add a new method for this in the next release (1.19).

**Comment by mingjunsiek** [comment]
awesome, this way, we won't have to rely on your side instead and let us do it our selves.

**Comment by umair13adil** [comment]
@dariocavada @mingjunsiek  New plugin version v1.0.19 is released, in that this issue is fixed:

```
if (Platform.isAndroid) {
    
      //Prominent disclosure
      await BeaconsPlugin.setDisclosureDialogMessage(
          title: "Need Location Permission",
          message: "This app collects location data to work with beacons.");

      //Only in case, you want the dialog to be shown again. By Default, a dialog will never be shown if permissions are granted.
      await BeaconsPlugin.clearDisclosureDialogShowFlag(false);
    }
```
