### ISSUE TITLE
iOS Build Issue - Module not found

### ISSUE THREAD

**Issue by eishon** [umair13adil/simple_beacons_flutter#40]
I am facing an issue during iOS app release build. The plugin works in the app as expected, but while archiving, the following error shows, "module beacons_plugin not found". How can I solve this?

**Comment by eishon** [comment]
I found the solve of problem. Sharing it here..(Lost the link of original post)

# close Xcode
# uncomment #platform :ios, '9.0' in the Podfile
# cd ./ios/
# pod install
# flutter clean # cancel by ctrl+c if it hangs up
# open ios/Runner.xcworkspace

then do the rest

**Comment by maulik9211** [comment]
Extending @eishon's answer

close Xcode
uncomment #platform :ios, '11.0' in the Podfile
**flutter pub get**
cd ./ios/
pod install
cd ..
flutter clean  
**flutter build ios**
open ios/Runner.xcworkspace

I had to add these two commands to make it work.
