### ISSUE TITLE
Scanning for beacons not working

### ISSUE THREAD

**Issue by cloudbreakstudios** [umair13adil/simple_beacons_flutter#46]
Currently having an issue implementing this plugin.  Tried the readme and the example on git but it is not detecting the beacon.

I also noticed that in the example the code in onPause and onResume is the wrong way around and so changed this

Is there a way to use this where you do not have to enter the UUID?  I basically need to be able to scan for all beacons and then print out the UUID and other details for each beacon detected.  I thought the stream would give us this, but again - this doesn't seem to be working

So in my example im testing on an Android Samsung Galaxy S8 using a Minew D15N.  For my implementation I will not know the UUID and need to detect all beacons within range.  I shall update here if I can work it out - but would appreciate if anyone has had this issue and found a solution could get back to me.

**Comment by sander121** [comment]
Are you on the most recent version 2.0.0? When I updated to this version my app stopped to detect any beacons, the version before that, 1.0.20, works for me.

**Comment by cloudbreakstudios** [comment]
It turns out I was trying to read UID from an Eddystone beacon.  I have switched to iBeacon and it is now being detected.
