### ISSUE TITLE
iOS allow monitoring beacon using just UUID

### ISSUE THREAD

**Issue by dariocavada** [umair13adil/simple_beacons_flutter#6]
As for android it would be useful to filter the beacons only with **uuid** and not necessarily having to pass minor, major, name. I checked the code, but didn't find this capability.

Instead of this:
```
      BeaconsPlugin.addRegionForIOS(
              "01022022-f88f-0000-00ae-9605fd9bb620", 1, 1, "BeaconName")
          .then((result) {
        print(result);
      });
```

Something like:
```
      BeaconsPlugin.addRegionForIOS(
              "01022022-f88f-0000-00ae-9605fd9bb620", null, null, null)
          .then((result) {
        print(result);
      });
```

Or just:
```
      BeaconsPlugin.addRegionForIOS(
              "01022022-f88f-0000-00ae-9605fd9bb620")
          .then((result) {
        print(result);
      });
```
Thank you.

**Comment by umair13adil** [comment]
Hi,

Thank you for your feedback, this will be taken care of in next release soon. 

Med venlig hilsen / Kind regards
 
Muhammad Umair Adil,
Sr. Software Engineer
