### ISSUE TITLE
Cannot compile my app with your plugin under flutter 3.0.0

### ISSUE THREAD

**Issue by bambinoua** [umair13adil/simple_beacons_flutter#64]
compileAndroidSdk 31
targetAndroidSdk 30
kotlinVersion 1.6.10

I see the error which is in attached image
![index](https://user-images.githubusercontent.com/45417992/170052656-2d69401d-2b80-41e9-8a18-88a6789b236c.jpg)

**Comment by JohnSchroeder99** [comment]
Anything on this yet? I would hate to spend time with this package and not be able to to do what i need.

**Comment by umair13adil** [comment]
@JohnSchroeder99 This issue is resolved in this version "2.0.8".
